config/routes.rb
Rails.application.routes.draw do

  resources	:bookings
  root 'flights#index'
  resources	:flights

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, :foreign_key => :id_takeoff, :class_name => "Flight"
  has_many :arriving_flights, :foreign_key => :id_landing, :class_name => "Flight"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passangers, :through => :booking_passangers, :source => :booking_passanger
  has_many :booking_passangers, :foreign_key => :booking_id, :class_name => "BookingPassenger"
  accepts_nested_attributes_for :passangers
end

app/models/booking_passenger.rb
class BookingPassenger < ActiveRecord::Base
  belongs_to :booking_passanger, :foreign_key => "passanger_id", :class_name => "Passanger"
  belongs_to :passanger_booking, :foreign_key => "booking_id", :class_name => "Passanger"
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from_airport, :foreign_key => :id_takeoff, :class_name => "Airport"
  belongs_to :to_airport, :foreign_key => :id_landing, :class_name => "Airport"
  has_many :bookings, :class_name => "Booking"
end

app/models/passanger.rb
class Passanger < ActiveRecord::Base
  has_many :bookings
  has_many :bookings,  :through => :booking_passangers, :source => :passanger_booking
  has_many :booking_passangers, :foreign_key => :passanger_id, :class_name => "BookingPassenger"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new
    @booking.flight = @flight
    @booking.date = params[:date]
    params[:tikets].to_i.times { @booking.passangers.build }
     #@count_passangers = params[:tikets].to_i
      #@booking.passengers.build


  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      #@booking.passengers.each { |p| PassengerMailer.thank_you_email(p).deliver! }
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
   def booking_params
     params.require(:booking).permit(:flight_id, :date,
     :passangers_attributes => [:name, :email] )

   end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    puts "params = #{params}"
    @flights_xml = Flight.all

    if params[:date]
    @date = DateTime.parse("#{params[:date][:year]}-#{params[:date][:month]}-#{params[:date][:day]}" )
    #puts "date = #{date.wday.class}"
    #week_day = Date::DAYNAMES[date.wday]
    #@flights = Flight.first(10)
    @flights = Flight.where("id_takeoff = ? AND id_landing = ? AND week_day = ? " , params[:from], params[:to], @date.wday).order(:depart)
    @flights = @flights.paginate(page:	params[:page])
    else
      @flights = Flight.paginate(page:	params[:page])
    end
    @airports = Airport.all.map{|a| [ a.name, a.id ] }
    @passengers = (1..4).map{|a| [ a, a ] }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @flights_xml}
      format.json { render json: @flights_xml }
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Booking Page</h1>
<fieldset>
  <legend>Trip Details</legend>
  <h3>Flight # <%= @flight.name %></h3>
  <h3>
  <%= @flight.from_airport.name %> -> <%= @flight.to_airport.name %>
  </h3>
  <h4>Date <%= @booking.date[0,10] %></h4>
  <%= form_for @booking do |f| %>
  <%= f.hidden_field :date %>
  <%= f.hidden_field :flight_id %>

      <%= f.fields_for :passangers do |passanger| %>

          <br>

          <%= passanger.label :name %>
          <%= passanger.text_field :name %>
          <br>
          <%= passanger.label :email %>
          <%= passanger.text_field :email %>
          <br>

      <% end %>

    <br>
    <%= f.submit "Booking" %>

  <% end %>
</fieldset>

app/views/bookings/show.html.erb
<h1>Booking Confirmation</h1>

<p>
  Thank you for booking your flight with flight-booker.
  Your confirmation # is <b><%= @booking.id %></b>.
</p>

<p>
  Flight #<%= @booking.flight.name %>: <%= @booking.flight.from_airport.name %> ->
  <%= @booking.flight.to_airport.name %> on
  <%= @booking.date[1,9] %>
  <%= @booking.flight.depart %>
</p>

<p>Pasangers</p>
<ol>
  <% @booking.passangers.each do |passanger| %>
  <li><%= "#{passanger.name}  #{passanger.email}"  %></li>
  <% end %>
</ol>

app/views/flights/_search.html.erb
<%= form_tag flights_path, method: 'get', autocomlete: 'on' do %>
<div>
<p>
<%= select_tag :from, options_for_select(@airports, params[:from]) %>
Airport from</p>
</div>
<div style = "float: rigth">
<p>
<%= select_tag :to, options_for_select(@airports, params[:to]) %>
Airport to</p>
</div>
<div >
<p>
<%= select_tag :tikets, options_for_select(@passengers, params[:tikets]) %>
Passengers</p>
</div>

<%= select_date(Date.today, prompt: {day: 'Choose day', month: 'Choose month', year: 'Choose year'}) unless params[:date]  %>
<%= select_date(@date, prompt: {day: 'Choose day', month: 'Choose month', year: 'Choose year'}) if params[:date]  %>
<%= submit_tag "Search", :name => nil, class: "button" %>
<% end %>

app/views/flights/_search_results.html.erb
<%= form_tag new_booking_path, method: 'get', autocomlete: 'on' do %>
<div class = "flights">
<%=	will_paginate	%>
<table>
<thead>
  <tr>
    <th width = "50">Select</th>
    <th width ="210">Flight</th>
    <th width ="110">From</th>
    <th width ="110">To</th>
    <th width ="150">Date</th>
    <th width ="150">Departs</th>
    <th width ="110">Duration</th>
  </tr>
</thead>
 <% @flights.each do |flight| %>
  <tbody>
    <tr>
      <td align="center"><%= radio_button_tag :flight_id, flight.id %></td>
      <td width ="210"><%= flight.name %></td>
      <td align="center"><%= flight.from_airport.name %></td>
      <td align="center"><%= flight.to_airport.name %></td>
      <td align="center"><%= @date.strftime('%F') if @date %></td>
      <td align="center"><%= flight.depart %></td>
      <td align="center"><%= "#{flight.flight_time.hour}:#{flight.flight_time.min}"%></td>
    </tr>
  </tbody>
<% end %>
</table>
<%=	will_paginate	%>
<div >
<%= submit_tag "Select Flight", :name => nil, class: "button" %>
<%= hidden_field_tag :tikets, params[:tikets] %>
<%= hidden_field_tag :date, @date %>
<% end %>

app/views/flights/index.html.erb
<%= render 'search' %>

<% unless @flights.nil? %>
    <%= render 'search_results' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>